# Generated by Django 6.0.3 on 2026-03-22 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('api_url', models.TextField()),
                ('http_method', models.TextField()),
                ('request_body', models.TextField()),
                ('response_body', models.TextField()),
                ('message_type', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'API Record',
                'verbose_name_plural': 'API Records',
                'db_table': 'api_records',
            },
        ),
    ]
