# Generated by Django 6.0.3 on 2026-03-24 08:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsCatalogItem',
            fields=[
                ('goodsId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('goodsName', models.TextField()),
                ('goodsCategory', models.TextField()),
                ('goodsBrand', models.TextField()),
                ('goodsUnitAmountValue', models.IntegerField()),
                ('goodsUnitAmountCurrency', models.TextField(default='MYR')),
                ('stockQuantity', models.IntegerField(default=0)),
                ('taxRate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Goods Catalog Item',
                'verbose_name_plural': 'Goods Catalog Items',
                'db_table': 'goods_catalog_items',
            },
        ),
    ]
