# Generated by Django 6.0.3 on 2026-03-22 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('paymentRequestId', models.TextField(primary_key=True, serialize=False)),
                ('acquirerId', models.TextField(blank=True)),
                ('paymentAmountValue', models.IntegerField()),
                ('paymentAmountCurrency', models.TextField()),
                ('paymentMethodType', models.TextField(blank=True)),
                ('paymentMethodId', models.TextField(blank=True)),
                ('customerId', models.TextField(blank=True)),
                ('paymentMethodMetaData', models.JSONField(blank=True, null=True)),
                ('isInStorePayment', models.BooleanField(default=False)),
                ('isCashierPayment', models.BooleanField(default=False)),
                ('inStorePaymentScenario', models.TextField(blank=True)),
                ('paymentExpiryTime', models.DateTimeField(blank=True, null=True)),
                ('paymentNotifyUrl', models.TextField(blank=True)),
                ('paymentRedirectUrl', models.TextField(blank=True)),
                ('splitSettlementId', models.TextField(blank=True)),
                ('settlementStrategy', models.JSONField(blank=True, null=True)),
                ('paymentId', models.TextField(blank=True)),
                ('paymentTime', models.DateTimeField(blank=True, null=True)),
                ('pspId', models.TextField(blank=True)),
                ('walletBrandName', models.TextField(blank=True)),
                ('mppPaymentId', models.TextField(blank=True)),
                ('customsDeclarationAmountValue', models.IntegerField(null=True)),
                ('customsDeclarationAmountCurrency', models.TextField(blank=True)),
                ('resultStatus', models.TextField(blank=True)),
                ('resultCode', models.TextField(blank=True)),
                ('resultMessage', models.TextField(blank=True)),
                ('paymentStatus', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Request',
                'verbose_name_plural': 'Payment Requests',
                'db_table': 'payment_requests',
            },
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('settlementId', models.TextField(primary_key=True, serialize=False)),
                ('paymentRequestId', models.TextField()),
                ('settlementAmountValue', models.IntegerField()),
                ('settlementCurrency', models.TextField()),
                ('quoteId', models.TextField(blank=True)),
                ('quotePrice', models.DecimalField(decimal_places=10, max_digits=20, null=True)),
                ('quoteCurrencyPair', models.TextField(blank=True)),
                ('quoteStartTime', models.DateTimeField(blank=True, null=True)),
                ('quoteExpiryTime', models.DateTimeField(blank=True, null=True)),
                ('quoteUnit', models.TextField(blank=True)),
                ('baseCurrency', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Settlement',
                'verbose_name_plural': 'Settlements',
                'db_table': 'settlements',
            },
        ),
    ]
