# Generated by Django 6.0.3 on 2026-03-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrequest',
            name='acquirerId',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='customerId',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='customsDeclarationAmountCurrency',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='inStorePaymentScenario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='mppPaymentId',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='paymentId',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='paymentMethodId',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='paymentMethodType',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='paymentNotifyUrl',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='paymentRedirectUrl',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='paymentStatus',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='pspId',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='resultCode',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='resultMessage',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='resultStatus',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='splitSettlementId',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='walletBrandName',
            field=models.TextField(blank=True, null=True),
        ),
    ]
