# Generated by Django 6.0.3 on 2026-03-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_paymentrequest_acquirerid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settlement',
            name='quoteId',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='settlement',
            name='quoteCurrencyPair',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='settlement',
            name='quoteUnit',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='settlement',
            name='baseCurrency',
            field=models.TextField(blank=True, null=True),
        ),
    ]
