# Generated by Django 6.0.3 on 2026-03-22 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderId', models.TextField(primary_key=True, serialize=False)),
                ('paymentRequestId', models.TextField(blank=True, null=True)),
                ('referenceOrderId', models.TextField(blank=True, null=True)),
                ('orderDescription', models.TextField(blank=True, null=True)),
                ('orderAmountValue', models.IntegerField(null=True)),
                ('orderAmountCurrency', models.TextField(blank=True, null=True)),
                ('merchantId', models.TextField(blank=True, null=True)),
                ('shippingName', models.JSONField(blank=True, null=True)),
                ('shippingPhoneNo', models.TextField(blank=True, null=True)),
                ('shippingAddress', models.JSONField(blank=True, null=True)),
                ('shippingCarrier', models.TextField(blank=True, null=True)),
                ('referenceBuyerId', models.TextField(blank=True, null=True)),
                ('buyerName', models.JSONField(blank=True, null=True)),
                ('buyerPhoneNo', models.TextField(blank=True, null=True)),
                ('buyerEmail', models.TextField(blank=True, null=True)),
                ('env', models.JSONField(blank=True, null=True)),
                ('indirectAcquirer', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='OrderGoods',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('orderId', models.TextField(blank=True, null=True)),
                ('referenceGoodsId', models.TextField(blank=True, null=True)),
                ('goodsName', models.TextField(blank=True, null=True)),
                ('goodsCategory', models.TextField(blank=True, null=True)),
                ('goodsBrand', models.TextField(blank=True, null=True)),
                ('goodsUnitAmountValue', models.IntegerField(null=True)),
                ('goodsUnitAmountCurrency', models.TextField(blank=True, null=True)),
                ('goodsQuantity', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Order Goods',
                'verbose_name_plural': 'Order Goods',
                'db_table': 'order_goods',
            },
        ),
    ]
