# Generated by Django 6.0.3 on 2026-03-22 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='buyerEmail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='buyerPhoneNo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='merchantId',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderAmountCurrency',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderAmountValue',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderDescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='referenceBuyerId',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='referenceOrderId',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='shippingCarrier',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='shippingPhoneNo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordergoods',
            name='goodsBrand',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordergoods',
            name='goodsCategory',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordergoods',
            name='goodsName',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordergoods',
            name='goodsQuantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ordergoods',
            name='goodsUnitAmountCurrency',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordergoods',
            name='goodsUnitAmountValue',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ordergoods',
            name='orderId',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordergoods',
            name='referenceGoodsId',
            field=models.TextField(blank=True, null=True),
        ),
    ]
