# Generated by Django 6.0.3 on 2026-03-22 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('merchantId', models.TextField(primary_key=True, serialize=False)),
                ('merchantName', models.TextField()),
                ('merchantDisplayName', models.TextField()),
                ('merchantRegisterDate', models.DateTimeField(blank=True, null=True)),
                ('merchantMCC', models.TextField(blank=True)),
                ('merchantAddress', models.JSONField(blank=True, null=True)),
                ('store', models.JSONField(blank=True, null=True)),
                ('registrationDetailLegalName', models.TextField(blank=True, null=True)),
                ('registrationDetailRegistrationType', models.TextField(blank=True, null=True)),
                ('registrationDetailRegistrationNo', models.TextField(blank=True, null=True)),
                ('registrationDetailRegistrationAddress', models.JSONField(blank=True, null=True)),
                ('registrationDetailBusinessType', models.TextField(blank=True, null=True)),
                ('websites', models.JSONField(blank=True, null=True)),
                ('productCodes', models.JSONField(blank=True, null=True)),
                ('registrationNotifyUrl', models.TextField(blank=True, null=True)),
                ('currency', models.TextField(blank=True)),
                ('resultCode', models.TextField(blank=True, null=True)),
                ('resultMessage', models.TextField(blank=True, null=True)),
                ('resultStatus', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Merchant',
                'verbose_name_plural': 'Merchants',
                'db_table': 'merchants',
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('registrationRequestId', models.TextField(primary_key=True, serialize=False)),
                ('productCodes', models.JSONField(blank=True, null=True)),
                ('referenceMerchantId', models.TextField()),
                ('resultStatus', models.JSONField(blank=True, null=True)),
                ('resultCode', models.JSONField(blank=True, null=True)),
                ('resultMessage', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'registration_records',
            },
        ),
        migrations.CreateModel(
            name='EntryCode',
            fields=[
                ('codeId', models.TextField(primary_key=True, serialize=False)),
                ('merchantId', models.TextField()),
                ('codeStartTime', models.DateTimeField()),
                ('codeExpireTime', models.DateTimeField()),
                ('status', models.TextField(default='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Entry Code',
                'verbose_name_plural': 'Entry Codes',
                'db_table': 'entry_codes',
            },
        ),
    ]
