# Generated by Django 6.0.3 on 2026-03-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryCode',
            fields=[
                ('codeId', models.TextField(primary_key=True, serialize=False)),
                ('merchantId', models.TextField()),
                ('codeStartTime', models.DateTimeField()),
                ('codeExpireTime', models.DateTimeField()),
                ('status', models.TextField(default='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Entry Code',
                'verbose_name_plural': 'Entry Codes',
                'db_table': 'entry_codes',
            },
        ),
    ]
