# Generated by Django 6.0.3 on 2026-03-26 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='currency',
            field=models.TextField(blank=True, default='MYR'),
        ),
        migrations.AddField(
            model_name='registration',
            name='resultCode',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='resultMessage',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='resultStatus',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='registrationDetailLegalName',
            field=models.TextField(blank=True, null=True),
        ),
    ]
