# Generated by Django 6.0.3 on 2026-03-25 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='currency',
            field=models.TextField(blank=True, default='MYR'),
        ),
    ]
