# Generated by Django 6.0.3 on 2026-03-22 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RefundRecord',
            fields=[
                ('refundRequestId', models.TextField(primary_key=True, serialize=False)),
                ('paymentRequestId', models.TextField(blank=True, null=True)),
                ('paymentId', models.TextField(blank=True, null=True)),
                ('refundAmountValue', models.IntegerField()),
                ('refundAmountCurrency', models.TextField()),
                ('refundReason', models.TextField(blank=True, null=True)),
                ('resultCode', models.TextField(blank=True, null=True)),
                ('resultMessage', models.TextField(blank=True, null=True)),
                ('resultStatus', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Refund Record',
                'verbose_name_plural': 'Refund Records',
                'db_table': 'refund_records',
            },
        ),
    ]
