# Generated by Django 6.0.3 on 2026-03-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refunds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refundrecord',
            name='refundReason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
