# Generated by Django 6.0.3 on 2026-03-26 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refunds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='refundrecord',
            name='resultCode',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='refundrecord',
            name='resultMessage',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='refundrecord',
            name='resultStatus',
            field=models.TextField(blank=True, null=True),
        ),
    ]
